export default [
  {type: 'textUI'},
  {type: 'textImageUI'},
  {type: 'heroUI'},
  {type: 'contactsUI'},
  {type: 'listCardImageTextUI'},
  {type: 'listLieuUI'},
  {type: 'listStudioUI'},
  {type: 'listLModulaireUI'},
  {type: 'listPageUI'},
  {type: 'imageUI'},
  {type: 'marqueeUI'},
  {type: 'splitImageTextUI'},
  // {type: 'sliderUI'},
  {type: 'callOutUI'},
  {type: 'heroSplitScrollUI'},
  {type: 'heroSplitUI'},
  {type: 'sliderCardImageTextUI'},
]
